/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/genres": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every genre that's been observed at least once, sorted by descending
         *     series count, then name. Powers the feed-filter autocomplete.
         */
        get: operations["list_genres"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pings the database and reports `ok` when reachable. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Across-all-providers refresh summary. */
        get: operations["metrics_providers_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/providers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detailed refresh metrics for a single provider. */
        get: operations["providers_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review-queue depth-over-time + median time-to-decision for the window. */
        get: operations["review_queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Across-all-sources summary over the requested window. */
        get: operations["metrics_sources_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/sources/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detailed metrics for a single source: summary + per-bucket counts. */
        get: operations["sources_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every registered metadata provider with its latest cache-refresh
         *     markers and the active-provider flag.
         */
        get: operations["list_providers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/refresh-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fan-out cache refresh for every registered provider. Returns a per-id
         *     triggered/skipped breakdown so the admin UI can render each result.
         */
        post: operations["refresh_all"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{id}/refresh-cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger an offline-cache refresh for the named provider. Same locking
         *     semantics as the scheduled refresh job; an in-flight refresh causes
         *     this request to report `skipped = true` without spawning a duplicate.
         */
        post: operations["refresh_cache"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List releases ordered by `observed_at` descending. Filters compose. */
        get: operations["list_releases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/unresolved": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Review queue: releases awaiting human attention.
         * @description Returns releases whose status is `unresolved`, `ambiguous`, or
         *     `review_pending`, each with the recorded review candidates so the UI
         *     can render a "pick the right match" panel without a second fetch.
         */
        get: operations["list_unresolved"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{id}/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Manually link a release to a series. Body shape:
         * @description - `{ "seriesId": 42 }` — link to an existing series row by internal id.
         *     - `{ "provider": "mangabaka", "externalId": "1677" }` — link by a
         *       provider's external id. If no `series_external_ids` row matches yet,
         *       the active provider's `get` is called to fetch metadata and create
         *       the series row before linking.
         */
        post: operations["link"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark a release as "not a series we care about". Drops candidates and
         *     pins the resolution status to `rejected` so the resolver leaves it
         *     alone on subsequent runs.
         */
        post: operations["reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-run the resolver against a single release. Useful after a provider
         *     refresh, a config change, or a manual edit.
         */
        post: operations["retry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List series ordered by last release timestamp (most recent first by default). */
        get: operations["list_series"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Series detail, including the resolved external-ID mappings. */
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/{id}/refresh-metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-fetch metadata for a series from the active provider and re-persist. */
        post: operations["refresh_metadata"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every registered discovery source with its last-poll markers. */
        get: operations["list_sources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/poll-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fan-out trigger for every registered source. Returns a per-source
         *     triggered/skipped result without aggregating: callers see the same
         *     per-source outcomes a series of single-source calls would have produced.
         */
        post: operations["poll_all"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{name}/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger a one-shot poll for the named source. Uses the same per-source
         *     mutex the cron job holds, so a manual kick during a scheduled tick is
         *     silently skipped (`skipped = true`).
         */
        post: operations["poll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregate counts surfaced by the frontend home page and review badge. */
        get: operations["stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tag analog of [`list_genres`]. Same shape, different table. */
        get: operations["list_tags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiErrorBody: {
            error: string;
            message: string;
        };
        ErrorKindBucket: {
            /** Format: int64 */
            count: number;
            /**
             * @description `None` is stored when a failure row pre-dates the error_kind helper
             *     or comes from an unwrapped legacy path; surface it as `unknown`.
             */
            kind: string;
        };
        ExternalIdDto: {
            externalId: string;
            externalUrl?: string | null;
            /** Format: int64 */
            fetchedAt: number;
            provider: string;
        };
        FetchLatencyDto: {
            /** Format: int64 */
            maxMs?: number | null;
            /** Format: double */
            p50Ms?: number | null;
            /** Format: double */
            p95Ms?: number | null;
        };
        Health: {
            status: string;
        };
        /**
         * @description Body for the manual-link endpoint. Exactly one of:
         *     - `seriesId`: link to an existing series row by internal id.
         *     - `provider` + `externalId`: link via the named provider's external id;
         *       the provider's `get` is called when no mapping exists yet.
         */
        LinkRequest: {
            externalId?: string | null;
            provider?: string | null;
            /** Format: int32 */
            seriesId?: number | null;
        };
        ManualPollResponse: {
            /** @description `false` when a previous tick is still in flight; the request is a no-op. */
            skipped: boolean;
            source: string;
            triggered: boolean;
        };
        PollAllResponse: {
            results: components["schemas"]["ManualPollResponse"][];
        };
        ProviderCacheState: {
            /** Format: int64 */
            bytesDownloaded?: number | null;
            cacheVersion?: string | null;
            /** Format: int64 */
            fetchedAt: number;
            /** Format: int64 */
            recordCount?: number | null;
            sourceUrl?: string | null;
        };
        /**
         * @description Per-provider config exposed to the admin UI. The api_key is reported as
         *     a boolean only; the raw value never leaves the process.
         */
        ProviderConfigDto: {
            apiBaseUrl: string;
            apiFallback: boolean;
            /**
             * @description `true` when an api_key is configured (any non-empty value). The
             *     actual key never appears in JSON; that's the whole point of stashing
             *     it in `.env`.
             */
            apiKeySet: boolean;
            /** Format: int32 */
            negativeCacheTtlDays: number;
            /** @description Runtime: whether the on-disk dump is currently loaded. */
            offlineCacheLoaded: boolean;
            offlineDumpConfigured: boolean;
            offlineDumpUrl?: string | null;
            offlineRefreshCron?: string | null;
            /** Format: int32 */
            timeoutSeconds: number;
        };
        ProviderDto: {
            active: boolean;
            config?: null | components["schemas"]["ProviderConfigDto"];
            displayName: string;
            id: string;
            lastRefresh?: null | components["schemas"]["ProviderCacheState"];
        };
        ProviderList: {
            items: components["schemas"]["ProviderDto"][];
        };
        ProviderMetricsBucket: {
            /** Format: int64 */
            bucketStart: number;
            /** Format: int64 */
            failureCount: number;
            /** Format: int64 */
            skippedCount: number;
            /** Format: int64 */
            successCount: number;
        };
        ProviderMetricsDetail: {
            /** Format: int64 */
            bucketSeconds: number;
            buckets: components["schemas"]["ProviderMetricsBucket"][];
            fetchLatency: components["schemas"]["FetchLatencyDto"];
            providerId: string;
            /** Format: int64 */
            rangeSeconds: number;
            /** Format: int64 */
            since: number;
            summary?: null | components["schemas"]["ProviderMetricsSummaryItem"];
            /** Format: int64 */
            until: number;
        };
        ProviderMetricsSummary: {
            items: components["schemas"]["ProviderMetricsSummaryItem"][];
            /** Format: int64 */
            rangeSeconds: number;
            /** Format: int64 */
            since: number;
            /** Format: int64 */
            until: number;
        };
        ProviderMetricsSummaryItem: {
            /** Format: int64 */
            bytesSum?: number | null;
            /** Format: int64 */
            failureCount: number;
            /** Format: int64 */
            lastStartedAt?: number | null;
            lastStatus?: string | null;
            providerId: string;
            /** Format: int64 */
            skippedCount: number;
            /** Format: int64 */
            successCount: number;
            /** Format: double */
            successRate?: number | null;
            /** Format: int64 */
            totalRuns: number;
        };
        RefreshAllResponse: {
            results: components["schemas"]["RefreshResponse"][];
        };
        RefreshResponse: {
            provider: string;
            /** @description `false` when a refresh is already in flight; the request is a no-op. */
            skipped: boolean;
            triggered: boolean;
        };
        ReleaseCounts: {
            /** Format: int64 */
            ambiguous: number;
            /** Format: int64 */
            rejected: number;
            /** Format: int64 */
            resolved: number;
            /** Format: int64 */
            reviewPending: number;
            /** Format: int64 */
            unresolved: number;
        };
        ReleaseDto: {
            ddlUrl?: string | null;
            externalId: string;
            files: string[];
            formats: string[];
            id: string;
            infoHash?: string | null;
            /** Format: int64 */
            lastResolveAttemptAt?: number | null;
            link: string;
            magnet?: string | null;
            /** Format: int64 */
            observedAt: number;
            /** Format: int64 */
            postedAt: number;
            /** Format: int32 */
            resolutionAttempts: number;
            /** Format: double */
            resolutionConfidence?: number | null;
            resolutionPath?: string | null;
            resolutionStatus: string;
            /** Format: int32 */
            seriesId?: number | null;
            /** Format: int64 */
            sizeBytes?: number | null;
            sourceKind: string;
            sourceName: string;
            title: string;
            torrentUrl?: string | null;
        };
        ReleasePage: {
            items: components["schemas"]["ReleaseDto"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int64 */
            total: number;
        };
        ResolutionOutcomeBreakdown: {
            /** Format: int64 */
            failed: number;
            /** Format: int64 */
            foreignId: number;
            /** Format: int64 */
            fuzzy: number;
            /** Format: int64 */
            knownId: number;
            /** Format: int64 */
            review: number;
        };
        ReviewCandidateDto: {
            reason?: string | null;
            /** Format: double */
            score: number;
            seriesCoverUrl?: string | null;
            /** Format: int32 */
            seriesId: number;
            seriesTitle: string;
        };
        ReviewQueueMetrics: {
            /** Format: int64 */
            closedCount: number;
            /** Format: int64 */
            rangeSeconds: number;
            /** Format: int64 */
            since: number;
            snapshots: components["schemas"]["ReviewQueueSnapshotDto"][];
            /**
             * Format: double
             * @description Median time (seconds) from observed to resolved, over closures in
             *     `[since, until)`. `null` when nothing closed.
             */
            timeToDecisionP50Seconds?: number | null;
            /** Format: int64 */
            until: number;
        };
        ReviewQueueSnapshotDto: {
            /** Format: int64 */
            ambiguousCount: number;
            /** Format: int64 */
            capturedAt: number;
            /** Format: int64 */
            oldestPendingSeconds?: number | null;
            /** Format: int64 */
            pendingCount: number;
            /** Format: int64 */
            reviewPendingCount: number;
            /** Format: int64 */
            unresolvedCount: number;
        };
        SeriesDetail: {
            alternateTitles: string[];
            canonicalTitle: string;
            coverUrl?: string | null;
            externalIds: components["schemas"]["ExternalIdDto"][];
            /** Format: int64 */
            firstSeenAt: number;
            genres: string[];
            /** Format: double */
            highestChapter?: number | null;
            /** Format: double */
            highestVolume?: number | null;
            /** Format: int32 */
            id: number;
            kind?: string | null;
            /** Format: int64 */
            lastReleaseAt: number;
            /** Format: int64 */
            metadataFetchedAt: number;
            metadataSource: string;
            owned: boolean;
            status?: string | null;
            tags: string[];
            /** Format: int32 */
            year?: number | null;
        };
        SeriesListItem: {
            canonicalTitle: string;
            coverUrl?: string | null;
            /** Format: int64 */
            firstSeenAt: number;
            /** Format: int32 */
            id: number;
            kind?: string | null;
            /** Format: int64 */
            lastReleaseAt: number;
            owned: boolean;
            status?: string | null;
            /** Format: int32 */
            year?: number | null;
        };
        SeriesListPage: {
            items: components["schemas"]["SeriesListItem"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int64 */
            total: number;
        };
        /**
         * @description Operator-facing snapshot of the per-source config (the bits visible in
         *     `[[sources]]` and any kind-specific nested options). Never carries
         *     secrets; the source layer doesn't have any in v1.
         */
        SourceConfigDto: {
            cron?: string | null;
            enabled: boolean;
            /**
             * @description Feed URL for the source kind. Empty when the kind doesn't define one
             *     (every kind today does, so this is informational future-proofing).
             */
            feedUrl: string;
            fetchDetails: boolean;
            /** @description Override for the site base URL. Useful when the feed is proxied. */
            siteBaseUrl?: string | null;
            /** Format: int32 */
            timeoutSeconds: number;
        };
        SourceDto: {
            config?: null | components["schemas"]["SourceConfigDto"];
            kind: string;
            lastError?: string | null;
            /** Format: int64 */
            lastPolledAt?: number | null;
            /** Format: int64 */
            lastSuccessAt?: number | null;
            lastSummary?: string | null;
            name: string;
        };
        SourceList: {
            items: components["schemas"]["SourceDto"][];
        };
        SourceMetricsBucket: {
            /** Format: int64 */
            bucketStart: number;
            /** Format: int64 */
            failureCount: number;
            /** Format: int64 */
            fetchedSum?: number | null;
            /** Format: int64 */
            newSum?: number | null;
            /** Format: int64 */
            skippedCount: number;
            /** Format: int64 */
            successCount: number;
        };
        SourceMetricsDetail: {
            /** Format: int64 */
            bucketSeconds: number;
            buckets: components["schemas"]["SourceMetricsBucket"][];
            errorKinds: components["schemas"]["ErrorKindBucket"][];
            fetchLatency: components["schemas"]["FetchLatencyDto"];
            /** Format: int64 */
            rangeSeconds: number;
            /** Format: int64 */
            since: number;
            sourceName: string;
            summary?: null | components["schemas"]["SourceMetricsSummaryItem"];
            timeToResolution: components["schemas"]["TimeToResolutionDto"];
            /** Format: int64 */
            until: number;
        };
        SourceMetricsSummary: {
            items: components["schemas"]["SourceMetricsSummaryItem"][];
            /** Format: int64 */
            rangeSeconds: number;
            /** Format: int64 */
            since: number;
            /** Format: int64 */
            until: number;
        };
        SourceMetricsSummaryItem: {
            /** Format: int64 */
            failureCount: number;
            /** Format: int64 */
            fetchedSum?: number | null;
            /** Format: int64 */
            lastStartedAt?: number | null;
            lastStatus?: string | null;
            /** Format: int64 */
            newSum?: number | null;
            outcomes: components["schemas"]["ResolutionOutcomeBreakdown"];
            /** Format: int64 */
            resolvedSum?: number | null;
            /** Format: int64 */
            skippedCount: number;
            sourceName: string;
            /** Format: int64 */
            successCount: number;
            /**
             * Format: double
             * @description Convenience derivation: `successCount / (successCount + failureCount)`,
             *     `null` when the denominator is zero. Saves the client from a no-op
             *     division when nothing has run yet.
             */
            successRate?: number | null;
            /** Format: int64 */
            totalRuns: number;
        };
        StatsResponse: {
            activeProvider: string;
            releases: components["schemas"]["ReleaseCounts"];
            /** Format: int64 */
            series: number;
            /** Format: int64 */
            totalReleases: number;
        };
        TagList: {
            items: components["schemas"]["TagUsageDto"][];
        };
        TagUsageDto: {
            name: string;
            /** Format: int64 */
            seriesCount: number;
        };
        TimeToResolutionDto: {
            /** Format: int64 */
            count: number;
            /** Format: double */
            p50Seconds?: number | null;
            /** Format: double */
            p95Seconds?: number | null;
        };
        UnresolvedPage: {
            items: components["schemas"]["UnresolvedRelease"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int64 */
            total: number;
        };
        UnresolvedRelease: components["schemas"]["ReleaseDto"] & {
            candidates: components["schemas"]["ReviewCandidateDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_genres: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagList"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Database unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    metrics_providers_summary: {
        parameters: {
            query?: {
                /** @description Sliding window for the aggregate, e.g. `24h`, `7d`. Defaults to 24h. */
                range?: string;
                /** @description Number of equal-width buckets. Clamped to [4, 168]. Defaults to 24. */
                buckets?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderMetricsSummary"];
                };
            };
        };
    };
    providers_detail: {
        parameters: {
            query?: {
                /** @description Sliding window for the aggregate, e.g. `24h`, `7d`. Defaults to 24h. */
                range?: string;
                /** @description Number of equal-width buckets. Clamped to [4, 168]. Defaults to 24. */
                buckets?: number;
            };
            header?: never;
            path: {
                /** @description Provider id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderMetricsDetail"];
                };
            };
        };
    };
    review_queue: {
        parameters: {
            query?: {
                /** @description Sliding window for the aggregate, e.g. `24h`, `7d`. Defaults to 24h. */
                range?: string;
                /** @description Number of equal-width buckets. Clamped to [4, 168]. Defaults to 24. */
                buckets?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewQueueMetrics"];
                };
            };
        };
    };
    metrics_sources_summary: {
        parameters: {
            query?: {
                /** @description Sliding window for the aggregate, e.g. `24h`, `7d`. Defaults to 24h. */
                range?: string;
                /** @description Number of equal-width buckets. Clamped to [4, 168]. Defaults to 24. */
                buckets?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceMetricsSummary"];
                };
            };
        };
    };
    sources_detail: {
        parameters: {
            query?: {
                /** @description Sliding window for the aggregate, e.g. `24h`, `7d`. Defaults to 24h. */
                range?: string;
                /** @description Number of equal-width buckets. Clamped to [4, 168]. Defaults to 24. */
                buckets?: number;
            };
            header?: never;
            path: {
                /** @description Source instance name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceMetricsDetail"];
                };
            };
        };
    };
    list_providers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderList"];
                };
            };
        };
    };
    refresh_all: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshAllResponse"];
                };
            };
        };
    };
    refresh_cache: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Provider id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
            /** @description No provider with that id registered */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_releases: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                /** @description Filter by resolution status (`resolved`, `unresolved`, `ambiguous`, `review_pending`). */
                status?: string;
                sourceKind?: string;
                sourceName?: string;
                seriesId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleasePage"];
                };
            };
        };
    };
    list_unresolved: {
        parameters: {
            query?: {
                /** @description 1-indexed page number. */
                page?: number;
                /** @description Items per page (capped server-side at 200). */
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnresolvedPage"];
                };
            };
        };
    };
    link: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Release id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseDto"];
                };
            };
            /** @description Provider not registered or external_id unknown to provider */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Release or series not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Release id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseDto"];
                };
            };
            /** @description Release not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    retry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Release id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseDto"];
                };
            };
            /** @description Release not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_series: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                /** @description Filter by stored `series.type` (e.g. `manga`). */
                kind?: string;
                /** @description Filter by stored `series.status` (e.g. `ongoing`). */
                status?: string;
                /** @description Filter by ownership flag (true = owned by Codex, false = discoverable). */
                owned?: boolean;
                /** @description Filter by a single genre name. AND-combined with the other filters. */
                genre?: string;
                /** @description Filter by a single tag name. AND-combined with the other filters. */
                tag?: string;
                /** @description Sort field. Supports `last_release_at` (default) and `first_seen_at`. */
                sort?: string;
                /** @description `asc` or `desc` (default). */
                order?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesListPage"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Internal series id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesDetail"];
                };
            };
            /** @description No series with that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh_metadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Internal series id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesDetail"];
                };
            };
            /** @description Series or provider entry not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No mapping for the active provider on this series */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_sources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceList"];
                };
            };
        };
    };
    poll_all: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollAllResponse"];
                };
            };
        };
    };
    poll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Source instance name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualPollResponse"];
                };
            };
            /** @description No source with that name registered */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
        };
    };
    list_tags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagList"];
                };
            };
        };
    };
}
