/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/events/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Subscribe to manual-trigger lifecycle events as an SSE stream.
         * @description Auth: inherits the read auth gate (`auth.read_requires_auth`). The
         *     browser `EventSource` API cannot carry a custom `Authorization`
         *     header, so installs that flip `read_requires_auth=true` will need
         *     the operator's `api_key` to be sent via the
         *     `Authorization` header through a fetch-based polyfill, or the gate
         *     disabled for this single route. Default installs (`false`) work out
         *     of the box.
         */
        get: operations["events_jobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/genres": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every genre that's been observed at least once, sorted by descending
         *     series count, then name. Powers the feed-filter autocomplete.
         */
        get: operations["list_genres"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pings the database and reports `ok` when reachable. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the running binary's name and semver. Cheap, public, cache-forever. */
        get: operations["info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/id-maps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Foreign-id map sizes: `series_external_ids` counts grouped by provider,
         *     plus persisted MangaUpdates legacy → modern slug cache stats. Used by
         *     the admin "ID Maps" page; no range/bucketing applies because these
         *     numbers are not time-series.
         */
        get: operations["metrics_id_maps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Across-all-providers refresh summary. */
        get: operations["metrics_providers_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/providers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detailed refresh metrics for a single provider. */
        get: operations["providers_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review-queue depth-over-time + median time-to-decision for the window. */
        get: operations["review_queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Across-all-sources summary over the requested window. */
        get: operations["metrics_sources_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/sources/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detailed metrics for a single source: summary + per-bucket counts. */
        get: operations["sources_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every registered metadata provider with its latest cache-refresh
         *     markers and the active-provider flag.
         */
        get: operations["list_providers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/refresh-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fan-out cache refresh for every registered provider. Returns a per-id
         *     triggered/skipped breakdown so the admin UI can render each result.
         */
        post: operations["refresh_all_providers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{id}/refresh-cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger an offline-cache refresh for the named provider. Same locking
         *     semantics as the scheduled refresh job; an in-flight refresh causes
         *     this request to report `skipped = true` without spawning a duplicate.
         */
        post: operations["refresh_cache"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Title-or-externalId search against a single provider. Powers the
         *     review-queue "Link release" modal.
         * @description - `?externalId=<id>` — direct lookup via `MetadataProvider::get`.
         *     - `?q=<title>` — `MetadataProvider::search`, then enrichment via
         *       `get` on the top N hits and Dice-rescoring against `q`.
         *     - both empty → `400 Bad Request`.
         *     - unknown `id` → `404 Not Found`.
         */
        get: operations["search_provider"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List releases ordered by `observed_at` descending. Filters compose. */
        get: operations["list_releases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/bulk/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk-reject a set of review-queue releases. The body's `ids` (or, when
         *     empty, the filter fields) select the target set; every matched release is
         *     pinned to `rejected` and its candidates dropped in one set-based update.
         */
        post: operations["bulk_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/bulk/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk-retry a set of review-queue releases. The body's `ids` (or, when
         *     empty, the filter fields) select the target set (capped at the per-batch
         *     limit). Spawns a background batch under the shared retry-all lock and
         *     returns immediately; a concurrent retry-all / bulk-retry reports
         *     `skipped: true`. An empty match set is reported as `triggered: false`
         *     with `matched: 0` (no batch spawned, nothing skipped).
         */
        post: operations["bulk_retry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/retry-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-run the resolver against every release currently visible in the
         *     review queue (`unresolved`, `ambiguous`, `review_pending`). With
         *     `?includeResolved=true`, also walks `resolved` rows (skipping
         *     manually-linked ones). Spawns a background task and returns
         *     immediately so the request doesn't block on what can be a multi-
         *     minute walk. A dedicated per-process lock prevents a second click
         *     from spawning a parallel walk; in that case the response is
         *     `{ triggered: false, skipped: true }`.
         */
        post: operations["retry_all"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/unresolved": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Review queue: releases awaiting human attention.
         * @description Returns releases whose status is `unresolved`, `ambiguous`, or
         *     `review_pending`, each with the recorded review candidates so the UI
         *     can render a "pick the right match" panel without a second fetch.
         */
        get: operations["list_unresolved"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{id}/keep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark a release as a worthwhile standalone item that is not (and will
         *     never be) a tracked series: a guidebook, an artbook, a one-shot. Drops
         *     candidates and pins the status to `standalone` so the resolver leaves it
         *     alone; unlike `rejected`, these stay browsable in the "Kept" view.
         *     Re-run `retry` to pull one back into the resolution pipeline.
         */
        post: operations["keep"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{id}/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Manually link a release to a series. Body shape:
         * @description - `{ "seriesId": 42 }` — link to an existing series row by internal id.
         *     - `{ "provider": "mangabaka", "externalId": "1677" }` — link by a
         *       provider's external id. If no `series_external_ids` row matches yet,
         *       the active provider's `get` is called to fetch metadata and create
         *       the series row before linking.
         */
        post: operations["link"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark a release as "not a series we care about". Drops candidates and
         *     pins the resolution status to `rejected` so the resolver leaves it
         *     alone on subsequent runs.
         */
        post: operations["reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/releases/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-run the resolver against a single release. Useful after a provider
         *     refresh, a config change, or a manual edit.
         */
        post: operations["retry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List series ordered by last release timestamp (most recent first by default). */
        get: operations["list_series"];
        put?: never;
        /**
         * Create a manual series: a provider-less catalog entry for a real series
         *     the active provider lacks. The operator then links releases to it via
         *     `POST /releases/{id}/link` with `{ "seriesId": N }`.
         * @description No `series_external_ids` row is created, so this series never
         *     participates in auto-resolution (the fuzzy resolver searches the
         *     provider, not the local catalog) and is skipped by metadata refresh.
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/invalidate-metadata-hashes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clear `metadata_hash` for every provider-backed series row in scope so
         *     the next refresh tick rewrites them. The persist layer short-circuits
         *     the series UPDATE when the incoming provider payload hashes to the
         *     stored value; that's the right call for steady-state refreshes, but it
         *     strands existing rows whenever a new denormalized column lands on the
         *     `series` table (the upstream payload is unchanged → hash matches →
         *     write skipped → new column stays NULL forever).
         * @description This endpoint is the operator escape hatch for that scenario. It runs
         *     synchronously and returns the affected count; the operator then
         *     triggers `/series/refresh-all` (or waits for the next cron tick) to
         *     actually rewrite the rows.
         *
         *     Manual rows (`metadata_source = 'manual'`) are always left alone.
         */
        post: operations["invalidate_series_metadata_hashes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/refresh-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger a bulk refresh of stale series rows against the active
         *     metadata provider. The spawned tick reads `batch_size` and
         *     `min_age_days` from `metadata.series_refresh`; the same selection
         *     query backs the cron, so a manual click and a cron tick are
         *     behaviourally identical (and they share a per-provider mutex, so
         *     they can't race).
         * @description Returns immediately with `triggered: true` once the tick is spawned,
         *     or `triggered: false, skipped: true` when a refresh is already in
         *     flight for the active provider.
         */
        post: operations["refresh_all_series"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Series detail, including the resolved external-ID mappings. */
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series/{id}/refresh-metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-fetch metadata for a series from the active provider and re-persist. */
        post: operations["refresh_metadata"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every registered discovery source with its last-poll markers. */
        get: operations["list_sources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/poll-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fan-out trigger for every registered source. Returns a per-source
         *     triggered/skipped result without aggregating: callers see the same
         *     per-source outcomes a series of single-source calls would have produced.
         */
        post: operations["poll_all"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{name}/backfill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger an in-process historical backfill for the named source. Runs
         *     the same loop as the `tsundoku backfill` CLI, but inside the serve
         *     process under the shared per-source mutex, so it cannot race a cron
         *     poll (returns `skipped = true` when work is already in flight). Returns
         *     `422` when the source's kind does not support backfill.
         */
        post: operations["backfill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{name}/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger a one-shot poll for the named source. Uses the same per-source
         *     mutex the cron job holds, so a manual kick during a scheduled tick is
         *     silently skipped (`skipped = true`).
         */
        post: operations["poll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregate counts surfaced by the frontend home page and review badge. */
        get: operations["stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tag analog of [`list_genres`]. Same shape, different table. */
        get: operations["list_tags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiErrorBody: {
            error: string;
            message: string;
        };
        AppInfo: {
            name: string;
            version: string;
        };
        BulkRejectResponse: {
            /**
             * Format: int64
             * @description Number of releases moved to `rejected`.
             */
            rejected: number;
        };
        BulkRetryResponse: {
            /**
             * Format: int64
             * @description Number of releases the filters/ids matched (the batch size, capped at
             *     the per-batch limit).
             */
            matched: number;
            /** @description `true` when a prior retry batch is still in flight; the request is a no-op. */
            skipped: boolean;
            /** @description `true` when a batch was spawned by this request. */
            triggered: boolean;
        };
        /**
         * @description Shared body for the bulk review actions. The target set is either an
         *     explicit `ids` list (when non-empty) or every queue release matching the
         *     filter fields. An all-empty body targets the entire queue. The filters
         *     mirror [`ReviewQueueQuery`] so "select all matching" acts on exactly what
         *     the list endpoint shows; explicit `ids` are still intersected with the
         *     queue statuses so a decided release can't be re-acted on.
         */
        BulkReviewRequest: {
            /** @default null */
            format: string | null;
            /** @default [] */
            ids: string[];
            /** @default null */
            q: string | null;
            /** @default null */
            sourceName: string | null;
            /** @default null */
            status: string | null;
        };
        /**
         * @description Body for creating a manual series. Only `canonicalTitle` is required;
         *     the rest are optional descriptive fields. No provider mapping is created
         *     (that's the whole point), so the series is provider-agnostic and
         *     `metadataSource` is pinned to `manual`.
         */
        CreateSeriesRequest: {
            canonicalTitle: string;
            coverUrl?: string | null;
            description?: string | null;
            kind?: string | null;
            /** Format: int32 */
            year?: number | null;
        };
        ErrorKindBucket: {
            /** Format: int64 */
            count: number;
            /**
             * @description `None` is stored when a failure row pre-dates the error_kind helper
             *     or comes from an unwrapped legacy path; surface it as `unknown`.
             */
            kind: string;
        };
        ExternalIdDto: {
            externalId: string;
            /** Format: int64 */
            fetchedAt: number;
            provider: string;
        };
        ExternalIdMapCount: {
            /**
             * Format: int64
             * @description Number of `(provider, external_id) → series_id` rows recorded.
             */
            count: number;
            /** @description Canonical provider id (e.g. `mangaupdates`, `mal`, `anilist`). */
            provider: string;
        };
        /**
         * @description External provider links scraped from a release's description. Mirrors
         *     `td_source::ExternalLinks`; redefined here so we don't pull utoipa into
         *     the domain crate.
         */
        ExtractedLinksDto: {
            anilist?: string | null;
            mal?: string | null;
            mangadex?: string | null;
            mangaupdates?: string | null;
        };
        FetchLatencyDto: {
            /** Format: int64 */
            maxMs?: number | null;
            /** Format: double */
            p50Ms?: number | null;
            /** Format: double */
            p95Ms?: number | null;
        };
        Health: {
            status: string;
        };
        IdMapMetrics: {
            /**
             * @description Per-provider row counts from `series_external_ids`. Sorted
             *     alphabetically by provider for stable rendering.
             */
            externalIds: components["schemas"]["ExternalIdMapCount"][];
            /** @description State of the persisted MangaUpdates legacy → modern slug cache. */
            mangaupdatesRedirectCache: components["schemas"]["MangaupdatesRedirectStats"];
        };
        /**
         * @description Response from `POST /api/v1/series/invalidate-metadata-hashes`. The
         *     endpoint runs synchronously, so the counts are the actual outcome of
         *     the call (not "queued work").
         */
        InvalidateMetadataHashesResponse: {
            /**
             * Format: int32
             * @description Number of `series` rows whose `metadata_hash` was cleared. A
             *     subsequent series-refresh tick will rewrite each one because the
             *     hash short-circuit no longer fires.
             */
            invalidated: number;
            /**
             * @description Echoes the `provider` query parameter, or `null` when the call
             *     was not scoped.
             */
            provider?: string | null;
            /**
             * Format: int32
             * @description Number of rows that matched the scope but were left untouched
             *     because `metadata_source = 'manual'`. Reported so the operator
             *     can spot when a meaningful chunk of the catalog is curated by
             *     hand (and therefore not eligible for upstream refresh).
             */
            skippedManual: number;
        };
        /**
         * @description Single broadcast frame for the SSE channel. Always has `kind`, `id`,
         *     `phase`, and `at` (epoch millis); `result` is only populated on
         *     `Finished` events.
         */
        JobEvent: {
            /** Format: int64 */
            at: number;
            id: string;
            kind: components["schemas"]["JobKind"];
            phase: components["schemas"]["JobPhase"];
            result?: null | components["schemas"]["JobResult"];
        };
        /**
         * @description Kind of work an event refers to. Stays a plain string in the
         *     serialized form so the frontend can pattern-match without importing
         *     the enum.
         * @enum {string}
         */
        JobKind: "source" | "provider" | "seriesRefresh";
        /**
         * @description Lifecycle phase. `Started` fires after the per-key mutex was
         *     acquired (so a `skipped` job emits only `Finished`).
         * @enum {string}
         */
        JobPhase: "started" | "finished";
        /**
         * @description Compact result payload attached to a `finished` event. Optional
         *     per-trigger fields (fetched / new / resolved / bytes) are `None`
         *     when the trigger doesn't produce them.
         */
        JobResult: {
            /** Format: int64 */
            bytes?: number | null;
            /** Format: int64 */
            fetched?: number | null;
            /** Format: int64 */
            new?: number | null;
            /** Format: int64 */
            resolved?: number | null;
            skipped: boolean;
            triggered: boolean;
        };
        /**
         * @description Body for the manual-link endpoint. Exactly one of:
         *     - `seriesId`: link to an existing series row by internal id.
         *     - `provider` + `externalId`: link via the named provider's external id;
         *       the provider's `get` is called when no mapping exists yet.
         */
        LinkRequest: {
            externalId?: string | null;
            provider?: string | null;
            /** Format: int32 */
            seriesId?: number | null;
        };
        MangaupdatesRedirectStats: {
            /**
             * Format: int64
             * @description Epoch seconds of the most recent translation. `None` when the
             *     cache is empty.
             */
            lastResolvedAt?: number | null;
            /**
             * Format: int64
             * @description Rows where `modern_id IS NOT NULL` — legacy ids we've successfully
             *     translated to a slug.
             */
            modernCount: number;
            /**
             * Format: int64
             * @description Rows where `modern_id IS NULL` — legacy ids MU retired, so we no
             *     longer waste a HEAD request on them.
             */
            tombstoneCount: number;
        };
        ManualBackfillResponse: {
            /**
             * Format: int32
             * @description Pages the run was asked to walk (after clamping); it may stop early
             *     if the source runs out of history.
             */
            pages: number;
            /**
             * @description `true` when a poll or backfill for this source was already in
             *     flight; the request is a no-op.
             */
            skipped: boolean;
            source: string;
            triggered: boolean;
        };
        ManualPollResponse: {
            /** @description `false` when a previous tick is still in flight; the request is a no-op. */
            skipped: boolean;
            source: string;
            triggered: boolean;
        };
        PollAllResponse: {
            results: components["schemas"]["ManualPollResponse"][];
        };
        ProviderCacheState: {
            /** Format: int64 */
            bytesDownloaded?: number | null;
            cacheVersion?: string | null;
            /** Format: int64 */
            fetchedAt: number;
            /** Format: int64 */
            recordCount?: number | null;
            sourceUrl?: string | null;
        };
        /**
         * @description Per-provider config exposed to the admin UI. The api_key is reported as
         *     a boolean only; the raw value never leaves the process.
         */
        ProviderConfigDto: {
            apiBaseUrl: string;
            apiFallback: boolean;
            /**
             * @description `true` when an api_key is configured (any non-empty value). The
             *     actual key never appears in JSON; that's the whole point of stashing
             *     it in `.env`.
             */
            apiKeySet: boolean;
            /** Format: int32 */
            negativeCacheTtlDays: number;
            /** @description Runtime: whether the on-disk dump is currently loaded. */
            offlineCacheLoaded: boolean;
            offlineDumpConfigured: boolean;
            offlineDumpUrl?: string | null;
            offlineRefreshCron?: string | null;
            /** Format: int32 */
            timeoutSeconds: number;
        };
        ProviderDto: {
            active: boolean;
            config?: null | components["schemas"]["ProviderConfigDto"];
            displayName: string;
            id: string;
            lastRefresh?: null | components["schemas"]["ProviderCacheState"];
        };
        ProviderList: {
            items: components["schemas"]["ProviderDto"][];
        };
        ProviderMetricsBucket: {
            /** Format: int64 */
            bucketStart: number;
            /** Format: int64 */
            failureCount: number;
            /** Format: int64 */
            skippedCount: number;
            /** Format: int64 */
            successCount: number;
        };
        ProviderMetricsDetail: {
            /** Format: int64 */
            bucketSeconds: number;
            buckets: components["schemas"]["ProviderMetricsBucket"][];
            fetchLatency: components["schemas"]["FetchLatencyDto"];
            providerId: string;
            /** Format: int64 */
            rangeSeconds: number;
            /** Format: int64 */
            since: number;
            summary?: null | components["schemas"]["ProviderMetricsSummaryItem"];
            /** Format: int64 */
            until: number;
        };
        ProviderMetricsSummary: {
            items: components["schemas"]["ProviderMetricsSummaryItem"][];
            /** Format: int64 */
            rangeSeconds: number;
            /** Format: int64 */
            since: number;
            /** Format: int64 */
            until: number;
        };
        ProviderMetricsSummaryItem: {
            /** Format: int64 */
            bytesSum?: number | null;
            /** Format: int64 */
            failureCount: number;
            /** Format: int64 */
            lastStartedAt?: number | null;
            lastStatus?: string | null;
            providerId: string;
            /** Format: int64 */
            skippedCount: number;
            /** Format: int64 */
            successCount: number;
            /** Format: double */
            successRate?: number | null;
            /** Format: int64 */
            totalRuns: number;
        };
        /**
         * @description One enriched hit. `score` is Dice(`q`, `title`) for the title-search
         *     path, or `1.0` for the externalId short-circuit path.
         */
        ProviderSearchHit: {
            coverUrl?: string | null;
            externalId: string;
            genres: string[];
            kind?: string | null;
            /**
             * @description First alternate title, if any. Useful for showing the
             *     romaji/Japanese form alongside the canonical English title.
             */
            nativeTitle?: string | null;
            /** Format: float */
            score: number;
            status?: string | null;
            tags: string[];
            title: string;
            /** Format: int32 */
            totalChapters?: number | null;
            /**
             * Format: int32
             * @description Published volume/chapter counts from provider metadata, shown next to
             *     each hit so the operator can match a release against the series length.
             */
            totalVolumes?: number | null;
            /** Format: int32 */
            year?: number | null;
        };
        ProviderSearchResponse: {
            hits: components["schemas"]["ProviderSearchHit"][];
            provider: string;
        };
        RefreshAllResponse: {
            results: components["schemas"]["RefreshResponse"][];
        };
        /**
         * @description Response from `POST /api/v1/series/refresh-all`. Mirrors the
         *     triggered/skipped pattern used by the source and provider trigger
         *     endpoints. `batchSize` echoes the config value the spawned tick will
         *     use, so the operator can see at a glance how much work was queued.
         */
        RefreshAllSeriesResponse: {
            /**
             * Format: int32
             * @description Maximum number of series rows this tick will touch, copied from
             *     `metadata.series_refresh.batch_size`. Reported even on
             *     `skipped: true` so the UI can render consistent metadata.
             */
            batchSize: number;
            /**
             * Format: int32
             * @description Minimum age in days a row must have before it's eligible. Echoes
             *     `metadata.series_refresh.min_age_days`.
             */
            minAgeDays: number;
            /** @description Active provider id the refresh ran against. */
            provider: string;
            /**
             * @description `true` when a previous refresh tick is still in flight; the
             *     request is a no-op.
             */
            skipped: boolean;
            triggered: boolean;
        };
        RefreshResponse: {
            provider: string;
            /** @description `false` when a refresh is already in flight; the request is a no-op. */
            skipped: boolean;
            triggered: boolean;
        };
        ReleaseCounts: {
            /** Format: int64 */
            ambiguous: number;
            /** Format: int64 */
            rejected: number;
            /** Format: int64 */
            resolved: number;
            /** Format: int64 */
            reviewPending: number;
            /** Format: int64 */
            unresolved: number;
        };
        ReleaseDto: {
            ddlUrl?: string | null;
            /**
             * @description Raw description blob (markdown for Nyaa posts that ran detail fetch;
             *     the RSS anchor stub otherwise). Omitted when absent. Surfaced so the
             *     review and kept views can render it inline without opening the post.
             */
            descriptionHtml?: string | null;
            externalId: string;
            extractedLinks?: null | components["schemas"]["ExtractedLinksDto"];
            files: string[];
            formats: string[];
            id: string;
            infoHash?: string | null;
            /** Format: int64 */
            lastResolveAttemptAt?: number | null;
            link: string;
            magnet?: string | null;
            /** Format: int64 */
            observedAt: number;
            /** Format: int64 */
            postedAt: number;
            /** Format: int32 */
            resolutionAttempts: number;
            /** Format: double */
            resolutionConfidence?: number | null;
            resolutionPath?: string | null;
            resolutionStatus: string;
            /** Format: int32 */
            seriesId?: number | null;
            /** Format: int64 */
            sizeBytes?: number | null;
            sourceKind: string;
            sourceName: string;
            title: string;
            torrentUrl?: string | null;
        };
        ReleasePage: {
            items: components["schemas"]["ReleaseDto"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int64 */
            total: number;
        };
        ResolutionOutcomeBreakdown: {
            /** Format: int64 */
            failed: number;
            /** Format: int64 */
            foreignId: number;
            /** Format: int64 */
            fuzzy: number;
            /** Format: int64 */
            knownId: number;
            /** Format: int64 */
            review: number;
        };
        RetryAllResponse: {
            /** @description `true` when a prior retry-all batch is still in flight; the request is a no-op. */
            skipped: boolean;
            /** @description `true` when a batch was spawned by this request. */
            triggered: boolean;
        };
        ReviewCandidateDto: {
            /**
             * @description Alternate / native titles persisted on the series row. Surfaced
             *     in the review UI so romaji / Japanese / publisher variants are
             *     visible without opening the provider page.
             */
            alternateTitles: string[];
            externalId?: string | null;
            /**
             * @description Series format (manga / novel / manhwa / …) from provider metadata.
             *     Surfaced so the operator can sanity-check a candidate's format
             *     against the release before linking. `None` when the provider did
             *     not classify the series.
             */
            kind?: string | null;
            /**
             * @description Provider + external_id pair for building a link to the provider's
             *     page. Prefers the active provider's mapping; falls back to any
             *     other mapping so the operator always has a way to inspect the
             *     candidate. None when the series has no external IDs persisted.
             */
            provider?: string | null;
            reason?: string | null;
            /** Format: double */
            score: number;
            seriesCoverUrl?: string | null;
            /** Format: int32 */
            seriesId: number;
            seriesTitle: string;
            /** Format: int32 */
            totalChapters?: number | null;
            /**
             * Format: int32
             * @description Published volume/chapter counts from provider metadata. Let the
             *     operator compare the release's contents (see the torrent file list)
             *     against the candidate series' length. `None` when the provider did
             *     not expose them or the series predates this field.
             */
            totalVolumes?: number | null;
        };
        ReviewQueueMetrics: {
            /** Format: int64 */
            closedCount: number;
            /** Format: int64 */
            rangeSeconds: number;
            /** Format: int64 */
            since: number;
            snapshots: components["schemas"]["ReviewQueueSnapshotDto"][];
            /**
             * Format: double
             * @description Median time (seconds) from observed to resolved, over closures in
             *     `[since, until)`. `null` when nothing closed.
             */
            timeToDecisionP50Seconds?: number | null;
            /** Format: int64 */
            until: number;
        };
        ReviewQueueSnapshotDto: {
            /** Format: int64 */
            ambiguousCount: number;
            /** Format: int64 */
            capturedAt: number;
            /** Format: int64 */
            oldestPendingSeconds?: number | null;
            /** Format: int64 */
            pendingCount: number;
            /** Format: int64 */
            reviewPendingCount: number;
            /** Format: int64 */
            unresolvedCount: number;
        };
        SeriesDetail: {
            alternateTitles: string[];
            canonicalTitle: string;
            coverUrl?: string | null;
            description?: string | null;
            externalIds: components["schemas"]["ExternalIdDto"][];
            /** Format: int64 */
            firstSeenAt: number;
            genres: string[];
            /** Format: double */
            highestChapter?: number | null;
            /** Format: double */
            highestVolume?: number | null;
            /** Format: int32 */
            id: number;
            kind?: string | null;
            /** Format: int64 */
            lastReleaseAt: number;
            /** Format: int64 */
            metadataFetchedAt: number;
            metadataSource: string;
            owned: boolean;
            /**
             * Format: double
             * @description Provider rating on a 0-10 scale (normalized in the provider's
             *     mapping layer). `None` when the provider has no rating.
             */
            rating?: number | null;
            status?: string | null;
            tags: string[];
            /**
             * Format: int32
             * @description Published total chapter count from provider metadata. See
             *     [`Self::total_volumes`] for how this differs from `highest_chapter`.
             */
            totalChapters?: number | null;
            /**
             * Format: int32
             * @description Published total volume count from provider metadata. Distinct from
             *     [`Self::highest_volume`], which tracks the highest span observed
             *     across releases. `None` if the provider has no value for this row.
             */
            totalVolumes?: number | null;
            /** Format: int32 */
            year?: number | null;
        };
        SeriesListItem: {
            canonicalTitle: string;
            coverUrl?: string | null;
            /**
             * @description Short synopsis. The list UI clamps this to a few lines; the detail
             *     page shows it in full.
             */
            description?: string | null;
            /** Format: int64 */
            firstSeenAt: number;
            genres: string[];
            /** Format: int32 */
            id: number;
            kind?: string | null;
            /** Format: int64 */
            lastReleaseAt: number;
            /**
             * @description Provenance of the row's metadata (`offline_cache`, `api`, or `manual`).
             *     The browse UI flags `manual` series so they read differently from
             *     provider-backed ones (no cover/metadata is expected).
             */
            metadataSource: string;
            owned: boolean;
            /**
             * Format: double
             * @description Provider rating on a 0-10 scale; surfaced on the list view so a
             *     future sort-by-rating has a number to display.
             */
            rating?: number | null;
            /**
             * Format: int64
             * @description Number of releases currently linked to this series. Surfaced as a
             *     badge in the feed so manual re-links that orphan a series (zero
             *     releases) are visible at a glance. Matches what
             *     `GET /releases?seriesId=…` returns.
             */
            releaseCount: number;
            status?: string | null;
            tags: string[];
            /**
             * Format: int32
             * @description Published total chapter count from provider metadata; pair to
             *     [`Self::total_volumes`] for sort-by-chapter results.
             */
            totalChapters?: number | null;
            /**
             * Format: int32
             * @description Published total volume count from provider metadata; surfaced on
             *     the list view so sort-by-volume results have a number to display.
             */
            totalVolumes?: number | null;
            /** Format: int32 */
            year?: number | null;
        };
        SeriesListPage: {
            items: components["schemas"]["SeriesListItem"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int64 */
            total: number;
        };
        /**
         * @description Operator-facing snapshot of the per-source config (the bits visible in
         *     `[[sources]]` and any kind-specific nested options). Never carries
         *     secrets; the source layer doesn't have any in v1.
         */
        SourceConfigDto: {
            cron?: string | null;
            enabled: boolean;
            /**
             * @description Feed URL for the source kind. Empty when the kind doesn't define one
             *     (every kind today does, so this is informational future-proofing).
             */
            feedUrl: string;
            fetchDetails: boolean;
            /**
             * Format: int32
             * @description Maximum number of feed pages walked per poll. Always `1` today:
             *     no v1 source kind paginates inside the steady-state poll. Kept on
             *     the DTO as a placeholder for future paginated source kinds; the
             *     `backfill` CLI is the historical-catch-up path in the meantime.
             */
            maxPages: number;
            /** @description Override for the site base URL. Useful when the feed is proxied. */
            siteBaseUrl?: string | null;
            /** Format: int32 */
            timeoutSeconds: number;
        };
        SourceDto: {
            config?: null | components["schemas"]["SourceConfigDto"];
            kind: string;
            lastError?: string | null;
            /** Format: int64 */
            lastPolledAt?: number | null;
            /** Format: int64 */
            lastSuccessAt?: number | null;
            lastSummary?: string | null;
            name: string;
        };
        SourceList: {
            items: components["schemas"]["SourceDto"][];
        };
        SourceMetricsBucket: {
            /** Format: int64 */
            bucketStart: number;
            /** Format: int64 */
            failureCount: number;
            /** Format: int64 */
            fetchedSum?: number | null;
            /** Format: int64 */
            newSum?: number | null;
            /** Format: int64 */
            skippedCount: number;
            /** Format: int64 */
            successCount: number;
        };
        SourceMetricsDetail: {
            /** Format: int64 */
            bucketSeconds: number;
            buckets: components["schemas"]["SourceMetricsBucket"][];
            errorKinds: components["schemas"]["ErrorKindBucket"][];
            fetchLatency: components["schemas"]["FetchLatencyDto"];
            /** Format: int64 */
            rangeSeconds: number;
            /** Format: int64 */
            since: number;
            sourceName: string;
            summary?: null | components["schemas"]["SourceMetricsSummaryItem"];
            timeToResolution: components["schemas"]["TimeToResolutionDto"];
            /** Format: int64 */
            until: number;
        };
        SourceMetricsSummary: {
            items: components["schemas"]["SourceMetricsSummaryItem"][];
            /** Format: int64 */
            rangeSeconds: number;
            /** Format: int64 */
            since: number;
            /** Format: int64 */
            until: number;
        };
        SourceMetricsSummaryItem: {
            /** Format: int64 */
            failureCount: number;
            /** Format: int64 */
            fetchedSum?: number | null;
            /** Format: int64 */
            lastStartedAt?: number | null;
            lastStatus?: string | null;
            /** Format: int64 */
            newSum?: number | null;
            outcomes: components["schemas"]["ResolutionOutcomeBreakdown"];
            /** Format: int64 */
            resolvedSum?: number | null;
            /** Format: int64 */
            skippedCount: number;
            sourceName: string;
            /** Format: int64 */
            successCount: number;
            /**
             * Format: double
             * @description Convenience derivation: `successCount / (successCount + failureCount)`,
             *     `null` when the denominator is zero. Saves the client from a no-op
             *     division when nothing has run yet.
             */
            successRate?: number | null;
            /** Format: int64 */
            totalRuns: number;
        };
        StatsResponse: {
            activeProvider: string;
            releases: components["schemas"]["ReleaseCounts"];
            /** Format: int64 */
            series: number;
            /** Format: int64 */
            totalReleases: number;
        };
        TagList: {
            items: components["schemas"]["TagUsageDto"][];
        };
        TagUsageDto: {
            name: string;
            /** Format: int64 */
            seriesCount: number;
        };
        TimeToResolutionDto: {
            /** Format: int64 */
            count: number;
            /** Format: double */
            p50Seconds?: number | null;
            /** Format: double */
            p95Seconds?: number | null;
        };
        UnresolvedPage: {
            items: components["schemas"]["UnresolvedRelease"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int64 */
            total: number;
        };
        UnresolvedRelease: components["schemas"]["ReleaseDto"] & {
            candidates: components["schemas"]["ReviewCandidateDto"][];
            /**
             * @description Stable rule names that fired during cleanup (e.g. `strip_parens`,
             *     `split_alternates`). Rendered as badge chips on the review card.
             */
            cleanupRulesApplied: string[];
            /**
             * @description Search queries the title cleaner produced for this release
             *     (longest-first). Empty when the release predates the cleaner or
             *     failed to persist; the next resolve cycle backfills.
             */
            searchQueries: string[];
            topCandidate?: null | components["schemas"]["ReviewCandidateDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    events_jobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream of JobEvent frames */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
        };
    };
    list_genres: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagList"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Database unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppInfo"];
                };
            };
        };
    };
    metrics_id_maps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdMapMetrics"];
                };
            };
        };
    };
    metrics_providers_summary: {
        parameters: {
            query?: {
                /** @description Sliding window for the aggregate, e.g. `24h`, `7d`. Defaults to 24h. */
                range?: string;
                /** @description Number of equal-width buckets. Clamped to [4, 168]. Defaults to 24. */
                buckets?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderMetricsSummary"];
                };
            };
        };
    };
    providers_detail: {
        parameters: {
            query?: {
                /** @description Sliding window for the aggregate, e.g. `24h`, `7d`. Defaults to 24h. */
                range?: string;
                /** @description Number of equal-width buckets. Clamped to [4, 168]. Defaults to 24. */
                buckets?: number;
            };
            header?: never;
            path: {
                /** @description Provider id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderMetricsDetail"];
                };
            };
        };
    };
    review_queue: {
        parameters: {
            query?: {
                /** @description Sliding window for the aggregate, e.g. `24h`, `7d`. Defaults to 24h. */
                range?: string;
                /** @description Number of equal-width buckets. Clamped to [4, 168]. Defaults to 24. */
                buckets?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewQueueMetrics"];
                };
            };
        };
    };
    metrics_sources_summary: {
        parameters: {
            query?: {
                /** @description Sliding window for the aggregate, e.g. `24h`, `7d`. Defaults to 24h. */
                range?: string;
                /** @description Number of equal-width buckets. Clamped to [4, 168]. Defaults to 24. */
                buckets?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceMetricsSummary"];
                };
            };
        };
    };
    sources_detail: {
        parameters: {
            query?: {
                /** @description Sliding window for the aggregate, e.g. `24h`, `7d`. Defaults to 24h. */
                range?: string;
                /** @description Number of equal-width buckets. Clamped to [4, 168]. Defaults to 24. */
                buckets?: number;
            };
            header?: never;
            path: {
                /** @description Source instance name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceMetricsDetail"];
                };
            };
        };
    };
    list_providers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderList"];
                };
            };
        };
    };
    refresh_all_providers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshAllResponse"];
                };
            };
        };
    };
    refresh_cache: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Provider id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
            /** @description No provider with that id registered */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    search_provider: {
        parameters: {
            query?: {
                /** @description Free-text title query. Trimmed before use; ignored when empty. */
                q?: string;
                /**
                 * @description Direct provider external-id lookup. When set, the handler short-
                 *     circuits to `MetadataProvider::get` and returns at most one hit
                 *     with `score = 1.0`.
                 */
                externalId?: string;
                /**
                 * @description Maximum number of hits to enrich with full metadata. Defaults to
                 *     10; clamped to `[1, 50]` to keep the per-request cost bounded.
                 */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Provider id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderSearchResponse"];
                };
            };
            /** @description Both q and externalId missing or empty */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown provider id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_releases: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                /**
                 * @description Filter by resolution status (`resolved`, `unresolved`, `ambiguous`,
                 *     `review_pending`, `rejected`, `standalone`).
                 */
                status?: string;
                sourceKind?: string;
                sourceName?: string;
                seriesId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleasePage"];
                };
            };
        };
    };
    bulk_reject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkReviewRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkRejectResponse"];
                };
            };
        };
    };
    bulk_retry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkReviewRequest"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkRetryResponse"];
                };
            };
        };
    };
    retry_all: {
        parameters: {
            query?: {
                /**
                 * @description Also re-evaluate rows currently marked `resolved` (excluding
                 *     manually-linked ones). Use after changing format-type rules,
                 *     title-cleanup config, or the active provider's cache, when
                 *     previously-confident matches need to be reconsidered against the
                 *     new logic. `rejected`, `standalone`, and `manual`-path rows are
                 *     always excluded.
                 */
                includeResolved?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetryAllResponse"];
                };
            };
        };
    };
    list_unresolved: {
        parameters: {
            query?: {
                /** @description 1-indexed page number. */
                page?: number;
                /** @description Items per page (capped server-side at 200). */
                pageSize?: number;
                /**
                 * @description Free-text title substring match (case-insensitive). Whitespace-only
                 *     is treated as absent.
                 */
                q?: string;
                /** @description Restrict to a single source instance (`releases.source_name`). */
                sourceName?: string;
                /** @description Restrict to releases carrying this file format (e.g. `cbz`, `epub`). */
                format?: string;
                /**
                 * @description Narrow to one queue status. Ignored unless it's one of
                 *     `unresolved` / `ambiguous` / `review_pending`.
                 */
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnresolvedPage"];
                };
            };
        };
    };
    keep: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Release id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseDto"];
                };
            };
            /** @description Release not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    link: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Release id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseDto"];
                };
            };
            /** @description Provider not registered or external_id unknown to provider */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Release or series not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Release id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseDto"];
                };
            };
            /** @description Release not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    retry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Release id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseDto"];
                };
            };
            /** @description Release not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_series: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                /** @description Filter by stored `series.type` (e.g. `manga`). */
                kind?: string;
                /** @description Filter by stored `series.status` (e.g. `ongoing`). */
                status?: string;
                /** @description Filter by ownership flag (true = owned by Codex, false = discoverable). */
                owned?: boolean;
                /**
                 * @description Filter by whether any releases are linked to the series. `true`
                 *     keeps only series with ≥1 release; `false` keeps only orphaned
                 *     series (zero releases — often the residue of a manual re-link).
                 */
                hasReleases?: boolean;
                /**
                 * @description Comma-separated genre names. Combined with [`Self::genres_mode`]:
                 *     `any` (default) keeps series matching at least one; `all` keeps
                 *     only series matching every entry. Each entry is matched case-
                 *     insensitively. AND-combined with the other filters.
                 */
                genres?: string;
                /** @description `any` (default) or `all`. See [`Self::genres`]. */
                genresMode?: string;
                /** @description Comma-separated tag names. Mirrors [`Self::genres`]. */
                tags?: string;
                /** @description `any` (default) or `all`. See [`Self::tags`]. */
                tagsMode?: string;
                /**
                 * @description Sort field. Supports `last_release_at` (default), `first_seen_at`,
                 *     `total_volumes`, and `total_chapters`. The count sorts are
                 *     nullable-aware: rows without a provider value sink to the end
                 *     regardless of direction. Ignored when `q` is present (results
                 *     are ranked by relevance instead).
                 */
                sort?: string;
                /** @description `asc` or `desc` (default). */
                order?: string;
                /**
                 * @description Free-text query. When set, results are ranked by a Dice-coefficient
                 *     score against canonical + alternate titles, with a boost for FTS5
                 *     prefix matches. Whitespace-only is treated as absent.
                 */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesListPage"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSeriesRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesDetail"];
                };
            };
            /** @description canonicalTitle is empty */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    invalidate_series_metadata_hashes: {
        parameters: {
            query?: {
                /**
                 * @description Provider id to scope the invalidation to (e.g. `"mangabaka"`).
                 *     Optional. When absent, every provider-backed row is affected.
                 */
                provider?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidateMetadataHashesResponse"];
                };
            };
        };
    };
    refresh_all_series: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshAllSeriesResponse"];
                };
            };
            /** @description Active provider is not registered */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Internal series id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesDetail"];
                };
            };
            /** @description No series with that id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh_metadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Internal series id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesDetail"];
                };
            };
            /** @description Series or provider entry not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No mapping for the active provider on this series */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_sources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceList"];
                };
            };
        };
    };
    poll_all: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollAllResponse"];
                };
            };
        };
    };
    backfill: {
        parameters: {
            query?: {
                /**
                 * @description Number of listing pages to walk, starting at page 1. Clamped to a
                 *     minimum of 1.
                 */
                pages?: number;
            };
            header?: never;
            path: {
                /** @description Source instance name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualBackfillResponse"];
                };
            };
            /** @description No source with that name registered */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Source kind does not support historical backfill */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    poll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Source instance name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualPollResponse"];
                };
            };
            /** @description No source with that name registered */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
        };
    };
    list_tags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagList"];
                };
            };
        };
    };
}
