import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import apiSidebar from "./apiSidebar";

// Two top-level sidebars:
//
// - `tutorialSidebar` — handwritten operator documentation, grouped by
//   onboarding stage. Categories collapsible-by-default except the
//   first two (visible without clicking).
// - `apiSidebar` — auto-generated by docusaurus-plugin-openapi-docs
//   from web/openapi.json. Empty on a fresh checkout until
//   `gen-api-docs` runs; the conditional require in apiSidebar.ts
//   prevents a missing-file build failure.
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    "intro",
    "showcase",
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      items: ["getting-started", "configuration"],
    },
    {
      type: "category",
      label: "Operating tsundoku",
      collapsed: false,
      items: [
        "sources",
        "providers",
        "browse",
        "review-queue",
        "kept-releases",
        "admin-maintenance",
        "codex",
      ],
    },
    {
      type: "category",
      label: "Reference",
      items: ["architecture", "deployment", "troubleshooting"],
    },
  ],
  apiSidebar,
};

export default sidebars;
